### ISSUE TITLE
Change signature of "generate_potential(...)"-like methods to more common view

### ISSUE THREAD

**Issue by dithillobothrium** [electronic-structure/SIRIUS#18]
It would be useful to make signature of method like `generate_potential(Density& density)`. Now it is not convenient `generate_potential(mdarray full_density, ndarray magnetization)` because every new feature from density requires overwriting of the code

**Comment by toxa81** [comment]
I agree. As far as I remember, there was a mutual dependency of Density and Potential. That's why they are kept on the same "level". May be I'm mistaken and it's not the case any more.

**Comment by dithillobothrium** [comment]
Yes, they are still dependent. Hm...

**Comment by dithillobothrium** [comment]
May be it is possible to replace this function [https://github.com/electronic-structure/SIRIUS/blob/master/src/k_set.cpp#L60](url) to some solver, which will be dependent on `Kset` and `Potential`. Then it will break circular dependency.

**Comment by dithillobothrium** [comment]
May be it is possible to replace this function https://github.com/electronic-structure/SIRIUS/blob/master/src/k_set.cpp#L60 to some solver, which will be dependent on Kset and Potential. Then it will break circular dependency.

**Comment by dithillobothrium** [comment]
I did https://github.com/dithillobothrium/SIRIUS/commit/b6eae55cba991e9c1241252d4fbf764241debe8f
