### ISSUE TITLE
Several issues with the generated Fortran API

### ISSUE THREAD

**Issue by dev-zero** [electronic-structure/SIRIUS#309]
The Fortran API seems to have a couple of issues.

Looking at `sirius_set_atom_type_radial_grid` as an example with the following definition:

```fortran
subroutine sirius_set_atom_type_radial_grid(handler,label,num_radial_points,radial_points)
   implicit none
   type(C_PTR), intent(in) :: handler
   character(C_CHAR), dimension(*), intent(in) :: label
   integer(C_INT), intent(in) :: num_radial_points
   real(C_DOUBLE), intent(in) :: radial_points

   interface
      subroutine sirius_set_atom_type_radial_grid_aux(handler,label,num_radial_points, radial_points) bind(C, name="sirius_set_atom_type_radial_grid")
         use, intrinsic :: ISO_C_BINDING
         type(C_PTR), intent(in) :: handler
         character(C_CHAR), dimension(*), intent(in) :: label
         integer(C_INT), intent(in) :: num_radial_points
         real(C_DOUBLE), intent(in) :: radial_points
      end subroutine
   end interface

   call sirius_set_atom_type_radial_grid_aux(handler,label,num_radial_points,radial_points)
end subroutine sirius_set_atom_type_radial_grid
```
with the following C/C++ function:

```cpp
void sirius_set_atom_type_radial_grid(void*  const* handler__,
                                      char   const* label__,
                                      int    const* num_radial_points__,
                                      double const* radial_points__)
{
    GET_SIM_CTX(handler__);

    auto& type = sim_ctx.unit_cell().atom_type(std::string(label__));
    type.set_radial_grid(*num_radial_points__, radial_points__);
}
```

1. `use, intrinsic :: ISO_C_BINDING` is missing in the definition of `sirius_set_atom_type_radial_grid`. Since you are using types defined by the ISO C Bindings already there, you should be using the `use ...` already. My guess is that the `use ISO_C_BINDING` is "leaking in" from somewhere.
2. The argument `radial_points` is actually supposed to be an array, not a single element. Since the outer routine is supposed to be a native Fortran subroutine, the parameter should be a Fortran array and this kind of casting should be hidden from the user (but there is even a better solution, see next point).
3. Fortran does not guarantee for arrays to be contiguous (especially not when using array slicing or subarrays). While this way of addressing arrays works in C/C++, it is conceptually wrong in Fortran. Use an assumed-size specifier instead: `real(C_DOUBLE), dimension(*), intent(in) :: radial_points`
4. Simple values like single integers could be passed by value rather than by pointer: `integer(C_INT), value, intent(in) :: num_radial_points`. Making the respective function declaration in C cleaner and avoiding a pointer dereference.
5. The applied double wrapping seems to be pointless: you are still "leaking" the ISO C Binding types towards Fortran while not making the function easier to access or hiding some of the design decisions for the interface. This should probably be removed completely.
6. From the semantics should the handler type be of `intent(inout)` since every call is also modifying the contents the handler is pointing to and could possibly invalidate it.

For the given example, the functions should rather look like:

```fortran
   interface
      subroutine sirius_set_atom_type_radial_grid(handler,label,num_radial_points, radial_points) bind(C, name="sirius_set_atom_type_radial_grid_aux")
         use, intrinsic :: ISO_C_BINDING
         type(C_PTR), intent(inout) :: handler
         character(C_CHAR), dimension(*), intent(in) :: label
         integer(C_INT), value, intent(in) :: num_radial_points
         real(C_DOUBLE), dimension(*), intent(in) :: radial_points
      end subroutine
   end interface
```
with the following C/C++ implementation:

```cpp
void sirius_set_atom_type_radial_grid(void** handler__,
                                      char   const* label__,
                                      int  num_radial_points__,
                                      double const* radial_points__)
{
    GET_SIM_CTX(handler__);

    auto& type = sim_ctx.unit_cell().atom_type(std::string(label__));
    type.set_radial_grid(num_radial_points__, radial_points__);
}
```

**Comment by toxa81** [comment]
Hi!

1. You are looking at 'generated.f90' file which is not compiled by itself. It is included from 'sirius.f90' and there the 'use, intrinsic :: ISO_C_BINDING' is present. So it is not missing or "leaking in" from somewhere.
2. There are other Fortran codes that can store radial grids as 2d arrays, e.g. rgrid(npt_max, nat_type). In this case you can't pass rgrid(1:npt, iat) to the interface and accept an array. The only working solution is the current one: pass first element by pointer. 
3. Yes, this is an abusive use of arrays and we believe that if a Fortran developer knows that his arrays are  not continuous in memory, he should not pass them to a C++ library. 
4. The C interface guaranties that the variable passed by pointer is read-only by using int const *
5. No, it is not. It is a generic form used to handle optional arguments in other API functions. 
6. Well, handler is a pointer to  pointer. It is passed as 'in' because the handler itself is not modified. This is what 'intent(in)' guaranties. I'm not sure if you can express const correctness with pointers in Fortran in the same way as you do in C++, i.e. guarantee that a pointer will not modify the object to which it points.

**Comment by dev-zero** [comment]
1. ok, my bad, didn't check that
2. I might be missing something, but the following example works as expected:
```fortran
program main
   real, dimension(3)   :: a
   real, dimension(3,4) :: b
   integer              :: i, j

   do i=1,3
      a(i) = i-1
   end do
      
   do j=1,4
      do i=1,3
         b(i, j) = i-1 + (j-1)*3
      end do
   end do

   call foo(a, 3)
   call foo(b, 12)
   call foo(b(1:2,1:2), 4)
contains
   subroutine foo(arr, narr)
      real, dimension(*) :: arr
      integer            :: narr

      write (*,*) arr(1:narr)
   end subroutine
end program
```
3. the problem is that people can never safely assume their arrays are contiguous (especially not when using subarrays/slices), so they can never safely use this API. Furthermore, problems from doing it like this may be very hard to debug and can go unnoticed. I would therefore rather prefer correctness here and have 2 functions instead if necessary or force the user to copy to a 1d array prior to calling.
4. The point here is not the const correctness, but rather the simpler interface on C++ side and avoiding yet another pointer dereferencing. See also rule 179 in "Modern Fortran" (Clerman & Spector).
5. Yes, I saw that this kind of double wrapping is used in some functions to handle optional arguments, but especially since you are generating the code, you could be generating simple forwards without the extra function call in cases where there is no optional argument handling. If you want to keep the double-wrapping it would be really nice to provide a real Fortran API (for example accept Fortran strings instead of `C_CHAR` arrays which require a final `C_CHAR_NULL`, see also rule 178 in "Modern Fortran")
6. This point is more a matter of preference: by signaling everything as `intent(in)` you actually say that the function does not change the state of anything passed in, which for me is always a signal that there is a global state and (even though there are multiple handles) that I can't assume that different handles are fully independent.

**Comment by toxa81** [comment]
2) 3) 4) 5) - point taken. I have to check how easy it would be to modify the markup for the functions and generating python script
6) indeed, it's a matter of taste. For pointer to pointers both intent(in) and intent(inout) are misleading. Both allow to modify the target memory.

**Comment by dev-zero** [comment]
I can also work on that if you like and send a PR. The only thing I would have to know is how to extend the `@fortran` syntax for the generator for the `value` semantic and possibly also the `dimension(*)`.

**Comment by oschuett** [comment]
+1 for using proper Fortran strings.

Currently, in CP2K the terminating null character is passed on to [keyword_create](https://github.com/cp2k/cp2k/blob/master/src/input_cp2k_pwdft.F#L178) and causes trouble problems [later on](https://github.com/cp2k/cp2k/blob/master/tools/docker/scripts/test_manual.sh#L28). It should be rather straightforward to add/remove the null chars within the SIRIUS Fortran API.

**Comment by toxa81** [comment]
@oschuett I'm on it. There will be several changes which will break the current API, but will make interface better. I'm starting with passing native Fortran strings and logical variables. Then I'll see if I can improve the passing of arrays.

**Comment by toxa81** [comment]
@dev-zero , @oschuett 
I'm slowly cleaning up the F90 interface. A quick question: is it possible to force Fortran to not compile this code?

```
subroutine foo(aa)
real(8), intent(in), dimension(3) :: aa
write(*,*)aa
return
end subroutine

program test
implicit none
real(8) aa(3)
aa = (/1.d0, 2.d0, 3.d0/)
call foo(aa(1))

end program
```

Properly is should be `call foo(aa)`

**Comment by oschuett** [comment]
Within Fortran you can use the [C Preprocessor in the traditional mode](https://gcc.gnu.org/onlinedocs/gfortran/Preprocessing-and-conditional-compilation.html). If that doesn't solve your problem, maybe you could elaborate a bit about your goal?

**Comment by toxa81** [comment]
I want to pass arrays as arrays. Right now, in the example above, the `foo` subroutine takes array as argument, but the main program calls `foo(aa(1))` and it works. Is there a way to disallow that?

**Comment by dev-zero** [comment]
I have to dive into the standard again to check why that works and what it implies. So far I wasn't able to make the compiler error out (tried gfortran 10, Intel Fortran). Best bet if someone has access to it would be the NAG compiler. flang might also be a possibility since we only need parsing, no code generation.

**Comment by oschuett** [comment]
I think this is fine. At least gfortran is smart enough to detect when you pass in an array that is too small:

```
program test
implicit none

real(8) aa(2)  ! THIS IS TOO SMALL
aa = (/1.d0, 2.d0/)
call foo(aa(1))

contains

subroutine foo(aa)
real(8), intent(in), dimension(3) :: aa
write(*,*)aa
return
end subroutine

end program
```

```
Error: Actual argument contains too few elements for dummy argument ‘aa’ (2/3) at (1)
```

**Comment by toxa81** [comment]
Dear @dev-zero and @oschuett !
This is a test of the preliminary new API:
https://github.com/toxa81/SIRIUS/blob/sirius-7.0.0/apps/tests/test_fortran_api.f90
I can pass strings, logical and array variables as native Fortran. Do you think this is sufficient for CP2K?

**Comment by oschuett** [comment]
Looks good to me. The only reminiscence of the C bindings are the various handlers:
```
type(C_PTR) :: handler
type(C_PTR) :: kset
type(C_PTR) :: dft
```
Are they all interchangeable? Otherwise, you could wrap them into Fortran types to be on the safe side.

**Comment by toxa81** [comment]
Do you mean if I can pass by mistake a C_PTR handler to a wrong subroutine? Yes and it will crash the code. But I assume that introducing the type for each C_PTR handler is a nice extra feature, but not a critical one.

**Comment by oschuett** [comment]
> But I assume that introducing the type for each C_PTR handler is a nice extra feature, but not a critical one.

Right, that's just a nice to have.

**Comment by toxa81** [comment]
We introduced types for handlers, this was the missing bit to close the issue
