### ISSUE TITLE
XC functinals

### ISSUE THREAD

**Issue by toxa81** [electronic-structure/SIRIUS#333]
in xc_functional_base.hpp:
```
#if (XC_MAJOR_VERSION >= 4) && (XC_MINOR_VERSION >= 3)
    {"XC_LDA_X_1D_SOFT", XC_LDA_X_1D_SOFT},
    {"XC_LDA_X_1D_EXPONENTIAL", XC_LDA_X_1D_EXPONENTIAL},
#else
    {"XC_LDA_X_1D", XC_LDA_X_1D}, /* Exchange in 1D */
#endif
```
I cant find XC_LDA_X_1D_SOFT and XC_LDA_X_1D_EXPONENTIAL definitions in any xc_func.h header. @mtaillefumier where do this guys come from?

**Comment by mtaillefumier** [comment]
libxc git repository. comment the guilty lines since they will be included in the next version. I work with the git repository of libxc, libvdwxc, etc... But these lines have been there for some time already.
