### ISSUE TITLE
Issue with symmetrization of the hubbard occupation matrix

### ISSUE THREAD

**Issue by mtaillefumier** [electronic-structure/SIRIUS#385]
If we symmetrize the hubbard occupation matrix n_s, then the solver becomes crazy after few iterations and electrons fly away (wrong unsymmetrized density warning). This happened before the my wfc refactoring but we leave this work to QE so it was simply forgotten with time.

This does not occur if we do not explicitly symmetrize n_s. The symmetries procedure is identical to the procedure for the density matrix since it is the same function.

**Comment by toxa81** [comment]
@mtaillefumier I pushed a new branch `ldapu` with the new verification test19. It will crash on the stress tensor.

**Comment by toxa81** [comment]
@mtaillefumier is this issue resolved now?

**Comment by mtaillefumier** [comment]
We close this one as well.
