### ISSUE TITLE
Please change /bin/bash to /bin/sh

### ISSUE THREAD

**Issue by yurivict** [electronic-structure/SIRIUS#397]
https://github.com/electronic-structure/SIRIUS/blob/master/generate_options_header_file.sh#L1

```bash != sh```
On many systems bash needs to be separately installed, and there is nothing that needs bash in this script.

**Comment by simonpintarelli** [comment]
@yurivict  Thank you for pointing this out! Changed in [develop](/electronic-structure/SIRIUS/tree/develop) : https://github.com/electronic-structure/SIRIUS/commit/b8c9c62c9cba46c0f0a2a50b4d0601af75f26d65
