### ISSUE TITLE
ROCM version cannot be built

### ISSUE THREAD

**Issue by s870582003** [electronic-structure/SIRIUS#423]
We are using Sirius on the ROCM platform with release v6.3.4.
However, ROCM version doesn't seems to be able to build successfully.
The build fail logs are appended below...
Also, we would like to ask if there is some comprehensive documentation on Sirius that covers 
a list of unit tests that needs to be passed, including the hand to hand steps to run them, and what to be expect int the correct output?

`[ 33%] Building CXX object src/CMakeFiles/sirius.dir/SDDK/wave_functions.cpp.o
[ 33%] Building CXX object src/CMakeFiles/sirius.dir/Hubbard/hubbard_generate_atomic_orbitals.cpp.o
[ 32%] Building CXX object src/CMakeFiles/sirius.dir/Band/diag_pseudo_potential.cpp.o
[ 33%] Building CXX object src/CMakeFiles/sirius.dir/Potential/xc.cpp.o
[ 20%] Building CXX object src/CMakeFiles/sirius.dir/SDDK/wf_trans.cpp.o
[ 33%] Building CXX object src/CMakeFiles/sirius.dir/dft_ground_state.cpp.o
[ 33%] Built target HIP_TARGET_random.cu
In file included from /home/sarahhung/Sirius/SIRIUS/src/SHT/sht.hpp:39:0,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/hubbard_orbitals_descriptor.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom_type.hpp:35,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom_symmetry_class.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom.hpp:29,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/unit_cell.hpp:29,
                 from /home/sarahhung/Sirius/SIRIUS/src/radial_integrals.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/radial_integrals.cpp:1:
/home/sarahhung/Sirius/SIRIUS/src/SDDK/linalg.hpp: In member function ‘void sddk::linalg2::trmm(char, char, char, ftn_int, ftn_int, const T*, const T*, ftn_int, T*, ftn_int, stream_id) const [with T = double; ftn_int = int]’:
/home/sarahhung/Sirius/SIRIUS/src/SDDK/linalg.hpp:214:87: error: too many arguments to function ‘void hipblas::dtrmm(char, char, char, char, int, int, const double*, const double*, int, double*, int)’
             gpublas::dtrmm(side, uplo, transa, 'N', m, n, alpha, A, lda, B, ldb, sid());
                                                                                       ^
In file included from /home/sarahhung/Sirius/SIRIUS/src/SDDK/GPU/gpublas_interface.hpp:34:0,
                 from /home/sarahhung/Sirius/SIRIUS/src/SDDK/linalg.hpp:30,
                 from /home/sarahhung/Sirius/SIRIUS/src/SHT/sht.hpp:39,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/hubbard_orbitals_descriptor.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom_type.hpp:35,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom_symmetry_class.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom.hpp:29,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/unit_cell.hpp:29,
                 from /home/sarahhung/Sirius/SIRIUS/src/radial_integrals.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/radial_integrals.cpp:1:
/home/sarahhung/Sirius/SIRIUS/src/SDDK/GPU/hipblas_interface.hpp:232:13: note: declared here
 inline void dtrmm(char side, char uplo, char transa, char diag, int m, int n, double const* alpha,
             ^~~~~
In file included from /home/sarahhung/Sirius/SIRIUS/src/SHT/sht.hpp:39:0,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/hubbard_orbitals_descriptor.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom_type.hpp:35,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom_symmetry_class.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/atom.hpp:29,
                 from /home/sarahhung/Sirius/SIRIUS/src/Unit_cell/unit_cell.hpp:29,
                 from /home/sarahhung/Sirius/SIRIUS/src/radial_integrals.hpp:28,
                 from /home/sarahhung/Sirius/SIRIUS/src/radial_integrals.cpp:1:
/home/sarahhung/Sirius/SIRIUS/src/SDDK/linalg.hpp: In member function ‘void sddk::linalg2::trmm(char, char, char, ftn_int, ftn_int, const T*, const T*, ftn_int, T*, ftn_int, stream_id) const [with T = std::complex<double>; ftn_int = int]’:
/home/sarahhung/Sirius/SIRIUS/src/SDDK/linalg.hpp:251:81: error: too many arguments to function ‘void hipblas::ztrmm(char, char, char, char, int, int, const hipDoubleComplex*, const hipDoubleComplex*, int, hipDoubleComplex*, int)’
                           reinterpret_cast<acc_complex_double_t*>(B), ldb, sid());
`
\

**Comment by toxa81** [comment]
@AdhocMan Simon, can you please have a look? As a side notice, I suggest to work with the latest `develop` branch.

**Comment by AdhocMan** [comment]
The ROCm support at moment is still experimental. The initial implementation was done with for an older release of ROCm and it may require some changes now. Due to the missing functionalities, only a very limited subset could be run anyway (mainly the FFT part, which has now been separated into a new library [SpFFT](https://github.com/eth-cscs/SpFFT)). Tests are available in the verification folder, but it is not yet possible to run them with ROCm.
The plan at moment is to wait for the missing parts before working on the ROCm integration again. 
In particular, what we are missing is:

- Complex number support in rocBLAS
- Eigensolver
- Additional LAPACK functionality such Cholesky factorization and inversion of triangular matrices

The last two points can be provided by the MAGMA library, once it supports ROCm.

**Comment by s870582003** [comment]
Ahhh I see. Can I assume that there is a stable version of Sirius that can be built and run successfully with some older version of Rocm? 
If so I, would you kindly provide the version tags for both Sirius and Rocm as I would like to try with that combination first.

**Comment by AdhocMan** [comment]
There is no stable support for ROCm. The experimental support was added with commit 7e886cc3b1f3239b38a9e1fba296f13d9dcfaf64 and targeted ROCm 2.1 or 2.2. However, you will not be able to use most functionality.
I recommend you wait with testing, until ROCm is fully supported (which depends on the missing features mentioned before).

**Comment by s870582003** [comment]
Ok I understand!
Thanks for the clarification!
