### ISSUE TITLE
CMake tries to copy headers without taking DESTDIR into account

### ISSUE THREAD

**Issue by merkys** [electronic-structure/SIRIUS#448]
On UNIX systems Makefile variable `DESTDIR` is usually used to provide root directory for the installation (see [`DESTDIR` documentation for CMake](https://cmake.org/cmake/help/v3.13/envvar/DESTDIR.html#envvar:DESTDIR)). One of instructions for SIRIUS however does not take `DESTDIR` into consideration:
```
cd obj-x86_64-linux-gnu && make -j1 install DESTDIR=<destdir>
...
Install the project...
/usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "None"
-- Installing: <destdir>/usr/lib/x86_64-linux-gnu/libsirius.a
Error copying directory from "sirius/obj-x86_64-linux-gnu/src/mod_files" to "/usr/include/sirius/".
```
I assume the following instruction in `src/CMakeLists.txt` is responsible for it:
```cmake
  INSTALL ( CODE
    "EXECUTE_PROCESS (COMMAND \"${CMAKE_COMMAND}\" -E copy_directory \"${PROJECT_BINARY_DIR}/src/mod_files\" \"${CMAKE_INSTALL_PREFIX}/include/sirius/\")"
    )
```
I assume the solution would be to use the following instruction instead:
```cmake
install(FILES ${PROJECT_BINARY_DIR}/src/mod_files "${CMAKE_INSTALL_PREFIX}/include/sirius")
```

**Comment by simonpintarelli** [comment]
This should fix it: https://github.com/electronic-structure/SIRIUS/commit/ee4fc7e8954614897e0982f0bf62b0097aa9cb75

I haven't noticed before that `make install DESTDIR=...` was broken. On archlinux it used to work.

**Comment by merkys** [comment]
This fixes the issue. Thanks for prompt response!
