### ISSUE TITLE
Wrong INTENT in Fortran API breaks compilation with GCC9

### ISSUE THREAD

**Issue by oschuett** [electronic-structure/SIRIUS#453]
In the generated Fortran API the second argument of `sirius_option_get_name_and_type()` is [falsely declared](https://github.com/electronic-structure/SIRIUS/blob/master/src/generated.f90#L2682) with `INTENT(out)`. As a result the compilation fails with GCC9:

![Screenshot from 2019-12-31 17-18-51](https://user-images.githubusercontent.com/241771/71717474-872a2380-2e18-11ea-98d7-959d657ee3d9.png)

This was [reported](https://groups.google.com/d/msg/cp2k/dbAKFiLrng8/aoM0-gTfBQAJ) in the CP2K forum.
The CP2K-CI does not yet test GCC9 as it is still using Ubuntu 18.04.

**Comment by toxa81** [comment]
fixed in the latest 'develop' branch; will appear in v6.4.3 tag

**Comment by toxa81** [comment]
This should be fixed now.

**Comment by mohamedsami144** [comment]
Thank you very much for your support.

**Comment by oschuett** [comment]
This is indeed fixed. See https://github.com/cp2k/cp2k/pull/707.
