### ISSUE TITLE
Build with Cmake with CUDA support 

### ISSUE THREAD

**Issue by zhujunmian** [electronic-structure/SIRIUS#462]
How to build the SIRIUS with cuda support by cmake? Should I set `CUDAROOT` or is the GPU-enabled version only works for other versions?

**Comment by simonpintarelli** [comment]
Having `nvcc` in your path should work, you can check using the command `which nvcc`. According to the cmake documentation
https://cmake.org/cmake/help/v3.16/module/FindCUDA.html?highlight=findcuda
you can also set the `CUDA_TOOLKIT_ROOT_DIR`:
`cmake -D CUDA_TOOLKIT_ROOT_DIR=/path/to/cuda`.

**Comment by toxa81** [comment]
and also, you need to add -DUSE_CUDA=1 -DGPU_MODEL='P100' to the cmake command
