### ISSUE TITLE
Use grid2grid

### ISSUE THREAD

**Issue by toxa81** [electronic-structure/SIRIUS#489]
There are several places where we perform reshuffling of wave-functions
 - for the FFT on a coarse mesh (to apply H_loc)
 - when we pass wave-functions from SIRIUS to QE
 - when we pass plane-wave coefficients between QE and SIRIUS

The idea is to switch to Marko's (@kabicm) grid2grid library. This will introduce another dependency, but reduce the amount of "custom" code in SIRIUS.

**Comment by kabicm** [comment]
A great idea @toxa81! I would be happy to help with this :)

**Comment by toxa81** [comment]
COSTA is now a hard dependency.
