### ISSUE TITLE
Move to new Fortran API

### ISSUE THREAD

**Issue by toxa81** [electronic-structure/SIRIUS#507]
@mtaillefumier @simonpintarelli @AdhocMan @haampie 

I plan to update the Fortran API. I propose to merge everything which is stable to `master` branch and tag it. Then I will update the `develop` branch with the new API and make a new `pre-release`. At this moment, QE and CP2K need to be adjusted to the new `pre-release`. Do you seen any obvious problems that I missed?

**Comment by haampie** [comment]
Seems fine to me. Is there any advantage of keeping the develop branch around actually?

**Comment by toxa81** [comment]
@haampie Yes, it helps to test new functionality. We had a short discussion here
https://github.com/electronic-structure/SIRIUS/issues/464

**Comment by mtaillefumier** [comment]
It seems fine to me as well. I will adjust cp2k when the new interface is in develop.
