### ISSUE TITLE
Possible race condition in sirius_initialize / sirius_finalize.

### ISSUE THREAD

**Issue by oschuett** [electronic-structure/SIRIUS#520]
Our [farming test](https://dashboard.cp2k.org/archive/farming/index.html) shows that `SIRIUS/regtest-1/He-full-potential.inp` is flaky, e.g. [here](https://dashboard.cp2k.org/archive/farming/commit_2a254cd6664e4ee9f48dc3c43bf55c3a0ef6dab5.txt).

A possible suspect is the [upgrade to SIRIUS 6.5.2](https://github.com/cp2k/cp2k/commit/f2ee233f29a848c692a1c097c5a48bb48eb20c22). However, I think the most likely cause is that I [enabled OpenMP](https://github.com/cp2k/cp2k/commit/1e4446c2b11e98aa5180285501cd38727b2f8b36).

What's special about the farming test is that it calls `sirius_initialize` / `sirius_finalize` multiple times. Hence, my guess is that there is a race condition where one thread is still doing finalize while the other is already in initialize.

**Comment by toxa81** [comment]
Hi Ole! From the output I see that the total energy in He is wrong. Is is the main issue, or is there something else in the output?

**Comment by oschuett** [comment]
Hi Anton, yes the total energy in He is wrong. However, it only happens sometimes and only in the farming test.

Regarding my original comment, I realized `sirius_initialize` / `sirius_finalize` can not actually overlap because they are not called within a parallel region. Nevertheless, farming is the only test where we re-initialize SIRIUS.

**Comment by toxa81** [comment]
I have something similar in the tests on Piz Daint. I call `srun -C gpu -N 4 ./test_script.x` and inside the script there is a loop over tests and which one is executes with mini-app. So there are multiple `sirius_initialize / sirius_finalize` calls within a single srun command. This fails randomly on different tests, somewhere inside MPI_Init(). This is not exactly what you have here, but might be related. I don't have any obvious solution to this. Simple two-liner test with MPI_Init/MPI_Finalize seems to work fine.

**Comment by oschuett** [comment]
Yes, they could be related. Your reproducer seems a lot more handy than mine. Note that in my case I'm **not** using the GPU.

**Comment by toxa81** [comment]
@oschuett is the issue resolved?

**Comment by oschuett** [comment]
We stopped testing SIRIUS with Farming a while ago. I just tried to reproduce it again today and couldn't. Since the issue has always been flaky, it might just have become less likely. That being said, it's certainly not a pressing problem for us anymore.
