### ISSUE TITLE
spack install all the things

### ISSUE THREAD

**Issue by haampie** [electronic-structure/SIRIUS#521]
This issue is to keep track of things we cannot yet install with `spack`. The obvious missing specs:

- [x] `elpa +cuda`: elpa is spack-installable, but we have to make it a CudaPackage upstream
- [x] `+rocm`:
  - [x] https://github.com/spack/spack/pull/18069
  - [x] https://github.com/spack/spack/pull/18068
  - [ ] hipMAGMA

pinging @simonpintarelli

**Comment by toxa81** [comment]
@AdhocMan what is the latest status of MAGMA/ROCm? Can it be installed with spack?

**Comment by AdhocMan** [comment]
It looks like ROCm support is part of the magma package now. But I haven't tested it myself.

**Comment by toxa81** [comment]
@haampie Looks like hipMAGMA is merged into main trunk, so it doesn't exist as a standalone packaged. The issue can be closed
