### ISSUE TITLE
test failure `sytrf returned 1`

### ISSUE THREAD

**Issue by haampie** [electronic-structure/SIRIUS#539]
- https://gitlab.com/cscs-ci/electronic-structure/SIRIUS/-/jobs/697370010
- https://gitlab.com/cscs-ci/electronic-structure/SIRIUS/-/jobs/708500528
- https://gitlab.com/cscs-ci/electronic-structure/SIRIUS/-/jobs/720599740
- https://gitlab.com/cscs-ci/electronic-structure/SIRIUS/-/jobs/720599743
- https://gitlab.com/cscs-ci/electronic-structure/SIRIUS/-/jobs/712341857

Seems like some issue with the broyden mixer where the matrix can get singular (close to convergence?)

**Comment by toxa81** [comment]
My big problem with this kind of error is that it doesn't happen always. Depending on the way it approaches the convergence (which slightly depends on the OMP threading) it might or might not appear :-/
