### ISSUE TITLE
Automated benchmarking

### ISSUE THREAD

**Issue by haampie** [electronic-structure/SIRIUS#566]
How about we add a simple github bot s.t. you can trigger benchmarks on PRs and individual commits.

**benchmarks:** Have a separate repo with benchmark problems

**triggering:** by commenting on github on PRs or individual commits
 - `@sirius_bot bench` -- just run benchmarks on this PR or commit
 - `@sirius_bot bench vs develop` -- run both this PR or commit and develop and compare
 - `@sirius_bot bench vs v6.5.7` -- run both this PR or commit and develop and compare

**reporting**: We could generate reports by pushing to a new folder in a dedicated github repo. For instance per benchmark the {stdout, stderr, `timers.json`, human-readable version of `timers.json`}. The bot could add a comment to the pr / commit it was triggered from. For comparisons between two commits, we can generate a report where we diff `timers.json` recursively and add some :arrow_up: and :arrow_down: symbols or percentages to see improvements / regressions.

**nightly tests**: make the bot comment on the latest commit in `develop` / `master` to trigger itself, then you can always just go tot the latest commit on github and find a link to the benchmark reports.

**q-e-sirius**: as long as we use timers.json, the same bot can work for `q-e-sirius`.

**Comment by toxa81** [comment]
I'm 100% for that!

**Comment by haampie** [comment]
Some more thoughts:

- I guess it is easiest to always build and benchmark both the 'current' and 'target' commits when commenting `@sirius_bot bench vs [target git ref]` instead of looking up whether a benchmark had already run on a certain commit.

Thing I'm not sure about:
- If we use spack, what version do we use? It's easiest to use the docker images we already have in CI, but they always have a recent version of spack. So, building for the same commit at different points in time might give different results as dependencies could have been updated.
- How to deal with (new) feature flags / build options / dependencies in PRs. Store environment files in a `benchmark/` folder for every different benchmark setup we want to test (e.g. `nividia-p100.yaml` and `cpu.yaml`)? 
- When using the docker images we already have with a recent spack version: the older commit being benchmarked against might have to rebuild many dependencies too, that causes some overhead. Maybe a useful optimization is to retain docker images of tagged versions, so that we don't have to rebuild all the time. If for some reason an old version has to be rebuilt because the spack API changed, we can manually delete the image and force a rebuild.

**Comment by toxa81** [comment]
We should aim at build reproducibility, this is for sure. We can concretise the spack builds. Say, we build with a given version of gcc and given version of libxc, spfft, etc. This should not depend much on the version of spack. To be on a safe side, we can use the fixed version of spack. 

I envision this like that: each night the (one built) fixed version of qe-sirius is benchmarked. This is to test the Daint environment for potential performance degradation. In theory we should observe the same performance with some small fluctuations. Another type of benchmark is the test of new PR. We have two options - build with the same concertized spack which we used for the reference benchmarks or build with the most fresh version of all packages. Then we can tell if the PR is suffering from performance degradation or new spack packages are making things worse. To compare the performance, we can use something like "not worse than 10% slowdown comparing with the best run over N previous days" or something along this line. Let's call team (@mtaillefumier @simonpintarelli @AdhocMan) for discussion.

**Comment by mtaillefumier** [comment]
Indeed, I do not think the version of spack will change anything concerning reproducibility. The version of the compiler and other dependencies is far more important. But keep in mind that we can not test all possible combination. 

We could go for instance with one build where all dependencies are fixed to reasonable versions and one build where everything is to the latest. The first case would allow us to test the cray environment (modulo mkl/mpich/cuda) keeping all other dependencies fixed. Testing new PR for performance is also good but it only makes sense with a fixed environment. I think all the options offered here are reasonable.

**Comment by simonpintarelli** [comment]
I think it would make sense to keep the dependencies (libxc, etc.) fixed, perhaps one could also use the versions which are used in daint EB modules. Triggering the benchmarks manually makes sense to me.

**Comment by haampie** [comment]
I'll just go for something along those lines:

- Be reasonably specific about versions of dependencies/compilers; I think I would just fix the minor version of deps, but keep the patch version open so we do get bug fixes from upstream.
- Build environment images: these are big, so let's just have one `latest` version per benchmark setup. This is what we do in normal CI too. Here we ensure there's a fairly recent version of spack installed. We can add some precompiled deps here, taken from what the current deps in the `develop` branch of SIRIUS. Also we can pull precompiled deps from the spack binary mirror on pollux.
- Deploy images: they can be a bit smaller, just a single `sirius.scf` command as entrypoint, stripped down to the minimum, no spack. We could keep these images around in a registry for tagged commits / or generally for x days.
- Generate a bench pipeline
  - build (and cache) deploy images, one for the current commit, one for the reference commit if not available already
  - run benchmarks for 'current' and 'reference', add timers.json as artifacts
  - post-process: collect the timers.json of benchmarks, diff them & report back to github.

**Comment by mtaillefumier** [comment]
All this is reasonable. Patch versions is also fine I think.

**Comment by haampie** [comment]
This is mostly implemented, except that you cannot really benchmark yet against old tagged versions that are lacking the `package.py` in the repo itself.
