### ISSUE TITLE
Compilation of Windows 10 with Cygwin64

### ISSUE THREAD

**Issue by maurosgroi** [electronic-structure/SIRIUS#596]
Dear developers,
my name is Mauro Sgroi.
I'm trying to compile Sirius 7.0.2 using SpFFT 0.9.13 on windos 10 using Cygwin64.
My cmake command is:

CXX=mpicxx CC=mpicc FC=mpif90 LIBXCROOT=/home/sgroi/apps/libxc LIBSPGROOT=/home/sgroi/apps/spglib cmake ../ -DSpFFT_DIR=/home/sgroi/apps/source/SpFFT-0.9.13/cmake/ -DCMAKE_INSTALL_PREFIX=/home/sgroi/apps/sirius

I get the following error:

CMake Error at /home/sgroi/apps/source/SpFFT-0.9.13/cmake/SpFFTConfigVersion.cmake:6 (include):
  include could not find load file:

    /home/sgroi/apps/source/SpFFT-0.9.13/cmake/SpFFTStaticConfigVersion.cmake
Call Stack (most recent call first):
  CMakeLists.txt:133 (find_package)

CMake Error at CMakeLists.txt:133 (find_package):
  Could not find a configuration file for package "SpFFT" that is compatible
  with requested version "0.9.13".

  The following configuration files were considered but not accepted:

    /home/sgroi/apps/source/SpFFT-0.9.13/cmake/SpFFTConfig.cmake, version: unknown

-- Configuring incomplete, errors occurred!

Even if the SpFFT source is in the right directory.

I tried different versions of SpFFT and Sirius and the problem is always the same.

Could you please give me some guidance?

Thanks a lot and best regards,
Mauro Sgroi.

**Comment by simonpintarelli** [comment]
Hello Mauro,

have you installed SpFFT, or is `/home/sgroi/apps/source/SpFFT-0.9.13` pointing to the source directory?

**Comment by maurosgroi** [comment]
Dear Simon,
thanks a lot for the help.
I'm using the source directory.
Should I proceed in a different way?
Best regards,
Mauro.

**Comment by simonpintarelli** [comment]
Yes, all the dependencies need to be installed, e.g. in case of `SpFFT` and `SPLA` using `cmake`, `make`, `make install`. Instead of installing it under Windows (we never tried compilation under windows so far), you could also use a docker container with preinstalled binaries. We could upload a container to dockerhub. Would this also work for you?

**Comment by maurosgroi** [comment]
Dear Simon,
thanks a lot.
I'm not sure I can install docker on my PC since it is a company computer.
I also tried to compile SpFFT but I don't know how to get it recognised by cmake in compiling SIRIUS.
Which directives should I use?
Is -DSpFFT_DIR correct? And for SPLA?

Thanks a lot and best regards,
Mauro.

**Comment by simonpintarelli** [comment]
Hi Mauro,

setting `CMAKE_PREFIX_PATH` to the installation directory, e.g. `/path/to/spFFT` which contains `lib` and `include`. 
Same for SPLA, e.g. `CMAKE_PREFIX_PATH=/path/to/spFFT:/path/to/SPLA` (separated by `:`) should work.

**Comment by maurosgroi** [comment]
Dear Simon,
I managed to compile SpFFT and SPLA. Sirius now founds them correctly and cmake works with no errors.
I used the following command:
CXX=mpicxx CC=mpicc FC=mpif90 SCALAPACKROOT=/home/sgroi/apps/scalapack LIBXCROOT=/home/sgroi/apps/libxc LIBSPGROOT=/home/sgroi/apps/spglib cmake ../ -DCMAKE_PREFIX=/home/sgroi/apps/sirius -DCMAKE_PREFIX_PATH='/home/sgroi/apps/spFFT;/home/sgroi/apps/spla;/home/sgroi/apps/openblas' -DUSE_CUDA=Off  -DUSE_MAGMA=Off -DUSE_SCALAPACK=On

Using make to compile I get a series of errors related to the missing execinfo.h header file:

make[2]: *** [src/CMakeFiles/sirius.dir/build.make:590: src/CMakeFiles/sirius.dir/radial/radial_integrals.cpp.o] Error 1
make[2]: *** [src/CMakeFiles/sirius.dir/build.make:408: src/CMakeFiles/sirius.dir/unit_cell/unit_cell_symmetry.cpp.o] Error 1
In file included from /home/sgroi/apps/source/SIRIUS-master/src/SDDK/memory.hpp:38,
                 from /home/sgroi/apps/source/SIRIUS-master/src/sht/gaunt.hpp:28,
                 from /home/sgroi/apps/source/SIRIUS-master/src/unit_cell/atom.hpp:28,
                 from /home/sgroi/apps/source/SIRIUS-master/src/unit_cell/unit_cell.hpp:29,
                 from /home/sgroi/apps/source/SIRIUS-master/src/lapw/matching_coefficients.hpp:29,
                 from /home/sgroi/apps/source/SIRIUS-master/src/k_point/k_point.hpp:28,
                 from /home/sgroi/apps/source/SIRIUS-master/src/k_point/k_point_set.cpp:22:
/home/sgroi/apps/source/SIRIUS-master/src/gpu/acc.hpp:44:10: fatal error: execinfo.h: No such file or directory
   44 | #include <execinfo.h>

Since that header is called by a fine in the GPU part of the code, is it possible to avoid calling it? I'm not using cuda.

Thanks a lot in advance and best regards,
Mauro.

**Comment by simonpintarelli** [comment]
Yes, it should be possible to comment `execinfo.h`, then you also need to comment the body of the function: 
https://github.com/electronic-structure/SIRIUS/blob/develop/src/gpu/acc.hpp#L120

It is used for the backtrace, but only called from device accelerated parts of the code, so it should not do any harm if you run on cpu.

**Comment by maurosgroi** [comment]
Dear Simon,
it works!
Thanks a lot and best regards,
Mauro.

**Comment by ltalirz** [comment]
if there is indeed interest in running sirius on windows, and it apparently works, would you be interested in adding a windows build to the [sirius conda feedstock](https://github.com/conda-forge/sirius-feedstock) so that everybody can profit from this?

I opened a PR here just to see what would still be missing https://github.com/conda-forge/sirius-feedstock/pull/3

**Comment by ltalirz** [comment]
Ah, after more careful reading I see that in the end you resorted to docker here.
Let's see what pops up in the PR

**Comment by haampie** [comment]
FWIW, you can also just install SIRIUS and its dependencies from sources on WSL2 natively for your architecture using spack, so that you get native compilation instead of generic binaries:

```
#  ubuntu.exe
$ apt-get update && apt-get install gcc g++ gfortran
$ curl -Lfso spack.x https://github.com/haampie/spack-batteries-included/releases/tag/develop
$ chmod +x spack.x
$ spack.x install sirius +cuda cuda_arch=... ^spfft cuda_arch=... ^intel-mkl
```

**Comment by toxa81** [comment]
@maurosgroi @simonpintarelli @haampie @ltalirz 
Is the issue resolved? Can I close it?

**Comment by simonpintarelli** [comment]
IMHO it's fine to close it.
