### ISSUE TITLE
CMake built for SIRIUS 7.0.2 with Intel/MKL 2021.* is failing

### ISSUE THREAD

**Issue by mkrack** [electronic-structure/SIRIUS#635]
Intel/MKL 2021.* provides no link `libmkl_def.so` to `libmkl_def.so.1`.
Changing SIRIUS-7.0.2/cmake/modules/FindMKL.cmake:73 from
```
  set(DEF_LIB "libmkl_def.so")
```
to
```
  set(DEF_LIB "libmkl_def.so.1")
```
is a possible fix.

**Comment by toxa81** [comment]
@simonpintarelli can you please have a look?

**Comment by simonpintarelli** [comment]
@mkrack Thank you for reporting this. I checked with intel-oneapi-mkl installed via spack and the link is indeed missing. Should have affected only the python api though, the rest does not link against it. It should be fixed in: #640

**Comment by mkrack** [comment]
@simonpintarelli Many thanks for fixing the issue.

Now, for SIRIUS v7.2.5 another problem appeared related to SpFFT and FindMKLSequential:
```
CMake Error at /data/user/krack/intel/2021.1/cmake/3.20.2/share/cmake-3.20/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "FindMKLSequential.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "MKLSequential", but CMake did not find one.

  Could not find a package configuration file provided by "MKLSequential"
  with any of the following names:

    MKLSequentialConfig.cmake
    mklsequential-config.cmake

  Add the installation prefix of "MKLSequential" to CMAKE_PREFIX_PATH or set
  "MKLSequential_DIR" to a directory containing one of the above files.  If
  "MKLSequential" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /data/user/krack/intel/2021.1/SpFFT/1.0.3/lib/cmake/SpFFT/SpFFTStaticConfig.cmake:22 (find_dependency)
  /data/user/krack/intel/2021.1/SpFFT/1.0.3/lib/cmake/SpFFT/SpFFTConfig.cmake:5 (include)
  CMakeLists.txt:138 (find_package)
```
It seems that the path defined line 22 of `SpFFT/1.0.3/lib/cmake/SpFFT/SpFFTStaticConfig.cmake`
`set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/modules")`
is wrong, since
`set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/../spfft/modules")`
works, but I am not sure, if that is a proper fix.

**Comment by simonpintarelli** [comment]
@AdhocMan can you please have a look? Same versions are working for me with spack.

**Comment by AdhocMan** [comment]
That was indeed a bug with the installation location of CMake modules. These are only used for the static library, so this hasn't shown up with the usual shared library builds.
There is now a new release that should fix this issue: https://github.com/eth-cscs/SpFFT/releases/tag/v1.0.4

**Comment by mkrack** [comment]
@AdhocMan many thanks for the quick fix. Now, the SIRIUS build works fine with Intel/MKL using SpFFT.
