### ISSUE TITLE
Setting RMT_MAX in control affects GK_CUTOFF calculation based on RMT_min

### ISSUE THREAD

**Issue by dev-zero** [electronic-structure/SIRIUS#693]
According to the documentation, GK_CUTOFF is calculated based on the AW_CUTOFF and the minimal muffin tin radius, taken from the element definition. This works, but as soon as I set RMT_MAX in the control section, the GK_CUTOFF changes while I'd expect the GK_CUTOFF calculation to remain the same and only the final muffin tin radius to be set to a max of of RMT_MAX.
Based on the naming of the variables this might be a bug?

**Comment by dev-zero** [comment]
... with sirius v7.2.7

**Comment by toxa81** [comment]
Hi Tiziano! Out of curiosity, can you provide a unit cell definition and initial MT radii (I guess they come from the species files). There is an extra-step in blowing up the muffin tin spheres which might affect the minimum found radius. I agree that it is unexpected behavior for the parameter of the the "control" section. I can move rmt_max out of there. The problem with automatic determination of MT radii is that it is not unique.

**Comment by dev-zero** [comment]
will be able to provide the files in the evening or on the weekend, until then, I've generated the basis with: `atom --symbol=C` and then tried the same input once with `RMT_MAX 1.1` and once without, and the calculated GK_CUTOFF changed (with a C4 system) while I expected the cutoff to always being calculated with the RMT_MIN of `0.65`.

**Comment by dev-zero** [comment]
basically trying to reproduce the exciting run from here: https://nomad-lab.eu/prod/rae/gui/entry/id/hyn062OhTxuVIXHALACrgg/Qh4POC5Q8Zea_gDgBIG9rcd03xhR/raw, now trying with a basis generated with `atom --symbol=C --core=1.1`.
Also, there seems to be some stability issues when it comes to using larger GK_CUTOFF (usually accompanied with a warning about negative interstitial charge), which makes it difficult to figure out whether I have that parameter converged.

**Comment by toxa81** [comment]
@dev-zero this is a good link, I can start from here

**Comment by dev-zero** [comment]
ok, so far it seems independent of the RMT, but as soon as the GK_CUTOFF is larger than ~7 convergence becomes difficult

**Comment by toxa81** [comment]
I checked the calculation. Its a high-accuracy run with hand-crafted species file. I will send you the carbon species. With mixing beta=0.3 it converges for a coarse [2,2,2] k-grid.

**Comment by toxa81** [comment]
gk_cutoff is a dependent variable of rgk_max (aw_cutoff in our language)
```
   if (full_potential()) {
          /* find the cutoff for G+k vectors (derived from rgkmax (aw_cutoff here) and minimum MT radius) */
          if (aw_cutoff() > 0) {
              gk_cutoff(aw_cutoff() / unit_cell().min_mt_radius());
          }
     ...
 ```
 If you want to control gk_cutoff, do not set aw_cutoff (keept it zero). This behaviour is consistent with Exciting code.
