### ISSUE TITLE
Wrong unsymmetrized density when using magma_gpu as a standard eigenvalue problem solver

### ISSUE THREAD

**Issue by dev-zero** [electronic-structure/SIRIUS#708]
Running some tests with CP2Ks regtests and SIRIUS I tried the [`Fe.inp`](https://github.com/cp2k/cp2k/blob/master/tests/SIRIUS/regtest-1/Fe.inp) and simply adapted it to use GPU with MAGMA as kind of a "smoketest".

With both the standard and the generalized eigenvalue solver set to `magma` it runs. With the generalized eigenvalue solver set to `magma_gpu` the calculation terminates with "not implemented". But with the standard eigenvalue solver set to `magma_gpu` I get:

```
SIRIUS INIT: FINISHED
SIRIUS UPDATE CONTEXT : FINISHED
[find] density_tol            : 1e-06
[find] energy_tol             : 1e-08
[find] itsol_tol (initial)    : 0.01
[find] itsol_tol_min          : 1e-13
[find] num_dft_iter           : 100

=== Warning at line 1417 of file /home/users/muellert/scratch/cp2k/tools/toolchain/build/SIRIUS-7.3.0/src/density/density.cpp ===
wrong unsymmetrized density
  obtained value : 3.035280e+01
  target value : 3.200000e+01
  difference : 1.647202e+00
...
```

**Comment by toxa81** [comment]
MAGMA gpu is very likely an obsolete feature which we likely drop. We now support cuSolver which covers all our needs.
