### ISSUE TITLE
Build error with sirius@7.2.7, 7.3.0 with gcc@9.4.0 using spack

### ISSUE THREAD

**Issue by payerle** [electronic-structure/SIRIUS#714]
I am encountering errors like
```console
/tmp/test_srvo3_pwpp.TFS7EC.ltrans64.ltrans.o: In function `sirius::K_point_set::create_k_mesh(geometry3d::vector3d<int>, geometry3d::vector3d<int>, int)':
<artificial>:(.text+0x74d4): undefined reference to `sirius::K_point<double>::generate_gklo_basis()'
collect2: error: ld returned 1 exit status
```
when trying to build sirius@7.2.7 or 7.3.0 using gcc@9.4.0 under spack.
Specifically trying to build in spack
```console
$ spack install sirius@7.2.7%gcc@9.4.0+apps ~boost_filesystem build_type=Release ~cuda ~elpa +fortran +ipo ~magma +memory_pool ~nlcglib +openmp +profiler +python ~rocm +scalapack ~shared ~single_precision +tests +vdwxc
```
using 
```console
$ spack debug report
* **Spack:** 0.17.0-319-5dce4d79bd
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo
```
(I have also updated the package.py for sirius with the copy from the latest devel branch of spack as of 2022-01-05 to try @7.3.0, with the same results).  I have since successfully compiled @7.2.6 with the same setup.  

I am submitting this report to sirius rather than spack as it looks to me like a sirius rather than spack error, and spack is the recommended installation procedure for sirius.

The full build output is:
[spack-build-out.txt](https://github.com/electronic-structure/SIRIUS/files/7815952/spack-build-out.txt)

**Comment by toxa81** [comment]
Hi @payerle ! I think it doesn't like disabling of shared libraries (`~shared` flag). Without it I compiled your spec:
`spack install sirius@7.3.0%gcc@9.4.0+apps ~boost_filesystem build_type=Release ~cuda ~elpa +fortran +ipo ~magma +memory_pool ~nlcglib +openmp +profiler +python ~rocm +scalapack ~single_precision +tests +vdwxc
`
Is it strictly necessary for your platform to not have the shared libraries? In our experience this is almost a mandatory options nowadays.

**Comment by simonpintarelli** [comment]
I can reproduce the error for `sirius@7.2.7+fortran~shared%gcc@9.4.0`, but only when adding `cxxflags=-flto -fno-fat-lto-objects`. Without the lto flags it compiles successfully for `~shared` and `+shared`.

**Comment by toxa81** [comment]
@simonpintarelli can you try the entire spec:
`spack install sirius@7.2.7%gcc@9.4.0+apps ~boost_filesystem build_type=Release ~cuda ~elpa +fortran +ipo ~magma +memory_pool ~nlcglib +openmp +profiler +python ~rocm +scalapack ~shared ~single_precision +tests +vdwxc`
didn't work for me on Ubuntu-20.04

**Comment by simonpintarelli** [comment]
Thanks, indeed `spack install sirius@7.2.7%gcc@9.4.0+apps ~boost_filesystem build_type=Release ~cuda ~elpa +fortran +ipo ~magma +memory_pool ~nlcglib +openmp +profiler +python ~rocm +scalapack ~shared ~single_precision +tests +vdwxc` fails for me as well. It seems the `+ipo` is guilty, which is adding the lto flags.

**Comment by payerle** [comment]
Thanks for the quick feedback.  The issue is academic for me at this time (I am a sysadmin and just updating our HPC software library, and @7.2.6 is current enough for us for now), and I was reporting in hopes that it would be addressed by the time my users start asking for @7.3 or later.  

The issue with the +ipo variant/lto flags is strange --- as I said I was able to compile sirius@7.2.6 using the same spack variants (including +ipo) and the same compiler.  So it seems to be related to a code change between @7.2.6 and @7.2.7

**Comment by simonpintarelli** [comment]
Version `7.2.7` introduced single precision computations and many classes were added a template parameter for the numeric type, the explicit template instantiation in different files seem to have caused this compilation error. It should be fixed in https://github.com/electronic-structure/SIRIUS/pull/715.

**Comment by toxa81** [comment]
I confirm, the PR(https://github.com/electronic-structure/SIRIUS/pull/715) fixes the issue.
