### ISSUE TITLE
errors during converting upf to json format

### ISSUE THREAD

**Issue by GengSS** [electronic-structure/SIRIUS#728]
Dear SIRIUS developers,
I'm learning to run the SIRIUS job in CP2K code, in which I need to convert the UPF format to json format to be read in CP2K,
However, when I am running the python script provided in the SIRIUS library, I encountered an error like this:

`Warning missing size field in attributes
Warning: missing size field in attributes <Element 'PP_NLCC' at 0x2ae59e526ea0>
Warning missing size field in attributes <Element 'PP_LOCAL' at 0x2ae59e526ef0>
`
One example is to convert the O.pbe-n-kjpaw_psl.1.0.0.UPF from the QE website,
It is not clear to me how to fix this error, and I greatly appricate any suggestions.

Thank you very much.

Best,
Geng

**Comment by simonpintarelli** [comment]
Hello Geng,

the python converter script is checking if the `<PP_NLCC>` tag has the size attribute. If it is found, it will check that the array found inside `PP_NLCC` has the same length as indicated. In case the size is not there, it will just read the array, print a warning, and assume that the UPF file was valid. There is nothing you can do on your side. If you trust the UPF file was written/generated correctly it is safe to ignore this warning.

Best regards,
Simon

**Comment by GengSS** [comment]
Dear Simon,
Thank you very much for your reply.

after running the python script, I did not find the generated *.json file,
It is my fault that I missed a link in the error message,

Here is all of them

Warning missing size field in attributes
Warning: missing size field in attributes <Element 'PP_NLCC' at 0x7fde4aea2e00>
Warning missing size field in attributes <Element 'PP_LOCAL' at 0x7fde4aea2e50>
Don't know how to parse this 'q_with_l != T'

Best,
Geng

**Comment by simonpintarelli** [comment]
Unfortunately, the script doesn't support this particular format of the augmentation (not implemented). Can you use the PAW pseudo from SSSP (https://www.materialscloud.org/discover/sssp/table/efficiency)?

**Comment by toxa81** [comment]
> Don't know how to parse this 'q_with_l != T'

Hi Geng
This should be fixed in the `develop` branch.  Here is the line: https://github.com/electronic-structure/SIRIUS/blob/develop/apps/upf/upf2_to_json.py#L121

**Comment by GengSS** [comment]
> > Don't know how to parse this 'q_with_l != T'
> 
> Hi Geng This should be fixed in the `develop` branch. Here is the line: https://github.com/electronic-structure/SIRIUS/blob/develop/apps/upf/upf2_to_json.py#L121

Dear toxa81,
thank you for you reply, but it still complains an error:

Warning: missing size field in attributes <Element 'PP_R' at 0x7fbe9151fd60>
Warning: missing size field in attributes <Element 'PP_NLCC' at 0x7fbe9151fe00>
Warning: missing size field in attributes <Element 'PP_LOCAL' at 0x7fbe9151fe50>
Traceback (most recent call last):
  File "./upf_to_json.py", line 45, in <module>
    main()
  File "./upf_to_json.py", line 34, in main
    pp_dict = parse_upf_from_string(upf_str)
  File "./upf_to_json.py", line 23, in parse_upf_from_string
    return parse_upf2_from_string(upf_str)
  File "/u/scratch/g/gengsun/sirus/upf3/upf2_to_json.py", line 334, in parse_upf2_from_string
    parse_PAW(upf_dict, root)
  File "/u/scratch/g/gengsun/sirus/upf3/upf2_to_json.py", line 220, in parse_PAW
    size = int(node.attrib['size'])
KeyError: 'size'

**Comment by toxa81** [comment]
Dear Geng!
Can you try now? I just pushed a few more fixes (https://github.com/electronic-structure/SIRIUS/commit/71f98d8e3c34eca625e94f3ae381f3b7cb04d21d). The main problem is that UPF doesn't have a common schema and from time to time we discover new UPFs that break our simple Python parser.

**Comment by GengSS** [comment]
> [71f98d8](https://github.com/electronic-structure/SIRIUS/commit/71f98d8e3c34eca625e94f3ae381f3b7cb04d21d))

Dear toxa81,
Thank you very much, It works

Best 
Geng
