### ISSUE TITLE
Switch to C++17

### ISSUE THREAD

**Issue by toxa81** [electronic-structure/SIRIUS#743]
@mtaillefumier @haampie @simonpintarelli @AdhocMan 
Is there any immediate reason why we can't switch to C++17?

**Comment by mtaillefumier** [comment]
Not that I am aware of.

**Comment by AdhocMan** [comment]
The only reason I can think of is NVCC, since switching to C++17 will require CUDA 11 or later.

**Comment by toxa81** [comment]
https://github.com/electronic-structure/SIRIUS/pull/776
