### ISSUE TITLE
Build fail due to probable ELPA api change

### ISSUE THREAD

**Issue by Tenshi65535** [electronic-structure/SIRIUS#773]
Greetings to all.

I 've tried to build SIRIUS 7.3.2 prerelease on Archlinux and got the error below:
```
SIRIUS-7.3.2/src/linalg/eigenproblem.hpp:744:9: error: ‘elpa_eigenvectors_all_host_arrays_dc’ was not declared in this scope; did you mean ‘elpa_eigenvectors_a_h_a_dc’?
  744 |         elpa_eigenvectors_all_host_arrays_dc(handle, A_ptr, w.get(), Z_ptr, &error);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         elpa_eigenvectors_a_h_a_dc
```
I've checked the ELPA documentation and the api seems change from ELPA-2021.11.002 to ELPA-2022.05.001.
Here are two links for your reference: [ELPA-2021.11.002](https://elpa.mpcdf.mpg.de/documentation/doxygen/ELPA_DOXYGEN_PAGES/ELPA-2021.11.002/html/elpa__generated_8h.html#aec77ea621ded890ace2ce6da83a0c1bc) and [ELPA-2022.05.001](https://elpa.mpcdf.mpg.de/documentation/doxygen/ELPA_DOXYGEN_PAGES/ELPA-2022.05.001/html/elpa__generated_8h.html#a3531667d2d62d20c92ee6b0154799693)

**Comment by toxa81** [comment]
again!?!? I will have a look. In spack ELPA-2021.11.001 is still the latest one, that's why we didn't capture it before.

**Comment by Eddie123e** [comment]
I've checked the commits of elpa git repo, and it seems only the procedure names changed in elpa_api.F90.
I guess a simple patch with versions specified would work?
Here is the link to the commit: [Commit095a65ea](https://gitlab.mpcdf.mpg.de/elpa/elpa/-/commit/095a65ea7c37033d600062da06c553bb787ee407).

**Comment by toxa81** [comment]
This will fix the problem https://github.com/electronic-structure/SIRIUS/pull/775
Todo:
[ ] @Eddie123e If I tag pre-release of sirius/7.3.3 from this branch, would that help?
[ ] Add ELPA-2022.05.001 to spack repo
[ ] Rebuild base CI/CD container with latest ELPA.

**Comment by toxa81** [comment]
Waiting for https://github.com/spack/spack/pull/33439 to be merged.

**Comment by toxa81** [comment]
shoule be resolved by now
