### ISSUE TITLE
Profiler incurs significant overhead

### ISSUE THREAD

**Issue by gsavva** [electronic-structure/SIRIUS#845]
Using the SIRIUS-enabled QE and running `hp.x`
After the `hp.x` run is finished, the SIRIUS profiler incurs a significant overhead.

Number reported below are from the attached file: [slurm-stdout.txt](https://github.com/electronic-structure/SIRIUS/files/11706445/slurm-stdout.txt)

Time reported after the last q-point converges: `Total CPU time :  2105.4 s` (35m 05s)
Time reported by SIRIUS profiler (1st line): `sirius          1       2.13 ks ....`
Time reported by QE, just before exiting: `HP           :      7h15m CPU      1h21m WALL` (4860 sec)

So the generation of the profiling information takes around 46 minutes!

By disabling the profiler, however, information on the execution time of the cg-solver is lost because this part is executed by SIRIUS.

For the attached run, I used 2 nodes on Piz Daint, 1 MPI rank per node, 12 threads per MPI rank.
For the same run, distributed over 16 nodes, 1 MPI rank per node, 12 threads per MPI rank, the overhead of the profiler is just 22 seconds

**Comment by toxa81** [comment]
The profile can be turned off in the production run. My guess is that we measure some very small and frequent functions that we don't need to mesure individually.

**Comment by AdhocMan** [comment]
The output also contains a warning:
`rt_graph WARNING: Start / stop time stamps do not match for "HP"!`
This suggests that there may also be a bug when using the profiler, where a profiling stop call is not always used after a start call. When processing the timings, this can cause a performance issue, since the entire timing tree has to be checked for the missing time stamp (potentially many times). Although there is quite a large number of profiler calls in general, so calling the timer functions too frequently may also be a problem.

**Comment by gsavva** [comment]
@AdhocMan indeed, this warning appears in all my `hp.x` runs but this significant overhead is not consistent...
It _seems_ to be happening only when a single node is used with many threads per MPI rank.
This could give some direction as to where the bug is.

For the 1-node run (as reported above), the `hp.x` runs for 35 mins and the overhead is 46 mins.
For the 16-nodes run, `hp.x` runs for 5m 32s and profiler's overhead is 22 sec.

**Comment by gsavva** [comment]
The warning is fixed on a commit on the q-e-sirius side: https://github.com/electronic-structure/q-e-sirius/commit/4a90fc06e651387d58f7ef79bb64480641c5fe02
SIRIUS was printing timer information before the hp run was properly finalized

**Comment by toxa81** [comment]
Let's monitor the performance and then close the issue.
