### ISSUE TITLE
Build fails with GCC 13

### ISSUE THREAD

**Issue by oschuett** [electronic-structure/SIRIUS#854]
GCC 13 [stopped including](https://gcc.gnu.org/gcc-13/porting_to.html) some common headers, causing the build to fail.

As a workaround I'm now using:
```
 sed -i '1 i\#include <cstdint>' src/*.hpp
```

**Comment by simonpintarelli** [comment]
Thanks for the report. Which SIRIUS version are you using? In develop branch it should have been fixed recently: https://github.com/electronic-structure/SIRIUS/pull/848

I've just tried again compiling `sirius@develop+fortran+apps+python%gcc@13`, it works for me.

**Comment by oschuett** [comment]
Thanks for the quick reply. I'm using the latest release version 7.4.3. Sorry, I didn't check the develop branch.
