### ISSUE TITLE
Update clang-format?

### ISSUE THREAD

**Issue by RMeli** [electronic-structure/SIRIUS#897]
The `clang-format.x` script uses `clang-format-12`:

https://github.com/electronic-structure/SIRIUS/blob/84a71b78c5fa964a78cffb0d4878874b15b107f0/clang_format.x#L5

`clang-format-12` is rather old (and no longer available via `apt` in Ubuntu 23). Should the `clang-format` version be updated?

[Commits can be ignored in the blame view](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view).

**Comment by simonpintarelli** [comment]
I'm using .clang-format via the IDE. But it seems indeed that ubuntu is not adding a symlink called `clang-format` (unless `/usr/lib/llvm-[ver]/bin` is in the path:

https://packages.ubuntu.com/kinetic/amd64/clang-format-15/filelist

**Comment by RMeli** [comment]
Fixed by #918
