### ISSUE TITLE
lmax in potential

### ISSUE THREAD

**Issue by toxa81** [electronic-structure/SIRIUS#9]
@dithillobothrium What's the story with lmax in potential. What lmax is necessary for PAW?

**Comment by dithillobothrium** [comment]
Because I need to use sht_, which is created here
https://github.com/electronic-structure/SIRIUS/blob/develop/src/Potential/potential.cpp#L63

Also I can create own SHT based lmax of each atom

**Comment by toxa81** [comment]
Yes, but what is lmax for this transformation? My guess is 2 * lmax_rf.

**Comment by dithillobothrium** [comment]
yes
