### ISSUE TITLE
Add sirius_get_version method to API

### ISSUE THREAD

**Issue by oschuett** [electronic-structure/SIRIUS#969]
It would be good if there was a way to query SIRIUS for its version number. See also https://github.com/cp2k/cp2k/issues/3286.

**Comment by simonpintarelli** [comment]
Thank you for the suggestion. I will add this to the fortran interface. What is the preferred format? 
```
sirius_get_version_major(int* v);
sirius_get_version_minor(int* v);
sirius_get_version_revision(int* v);
```
 or should it be returned as a string `major.minor.revision`?

**Comment by oschuett** [comment]
Thanks a lot for the quick implementation! The format is good.
